"""add_customer_credit_loyalty_models

Revision ID: 0a8c28a95feb
Revises: a1e89fa56d58
Create Date: 2025-11-30 09:07:08.418198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a8c28a95feb'
down_revision: Union[str, None] = 'a1e89fa56d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telegram_user_id', sa.Integer(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_credit', sa.Float(), nullable=False),
    sa.Column('total_paid', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('loyalty_points', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_payment_at', sa.DateTime(), nullable=True),
    sa.Column('last_sale_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_balance'), 'customer', ['balance'], unique=False)
    op.create_index(op.f('ix_customer_branch_id'), 'customer', ['branch_id'], unique=False)
    op.create_index(op.f('ix_customer_business_id'), 'customer', ['business_id'], unique=False)
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=False)
    op.create_index(op.f('ix_customer_telegram_user_id'), 'customer', ['telegram_user_id'], unique=False)
    op.create_table('customercreditentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('entry_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customercreditentry_business_id'), 'customercreditentry', ['business_id'], unique=False)
    op.create_index(op.f('ix_customercreditentry_created_at'), 'customercreditentry', ['created_at'], unique=False)
    op.create_index(op.f('ix_customercreditentry_customer_id'), 'customercreditentry', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customercreditentry_entry_type'), 'customercreditentry', ['entry_type'], unique=False)
    op.create_table('customerloyaltyentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('entry_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('points_after', sa.Float(), nullable=False),
    sa.Column('redemption_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('redemption_value', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customerloyaltyentry_business_id'), 'customerloyaltyentry', ['business_id'], unique=False)
    op.create_index(op.f('ix_customerloyaltyentry_created_at'), 'customerloyaltyentry', ['created_at'], unique=False)
    op.create_index(op.f('ix_customerloyaltyentry_customer_id'), 'customerloyaltyentry', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customerloyaltyentry_entry_type'), 'customerloyaltyentry', ['entry_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customerloyaltyentry_entry_type'), table_name='customerloyaltyentry')
    op.drop_index(op.f('ix_customerloyaltyentry_customer_id'), table_name='customerloyaltyentry')
    op.drop_index(op.f('ix_customerloyaltyentry_created_at'), table_name='customerloyaltyentry')
    op.drop_index(op.f('ix_customerloyaltyentry_business_id'), table_name='customerloyaltyentry')
    op.drop_table('customerloyaltyentry')
    op.drop_index(op.f('ix_customercreditentry_entry_type'), table_name='customercreditentry')
    op.drop_index(op.f('ix_customercreditentry_customer_id'), table_name='customercreditentry')
    op.drop_index(op.f('ix_customercreditentry_created_at'), table_name='customercreditentry')
    op.drop_index(op.f('ix_customercreditentry_business_id'), table_name='customercreditentry')
    op.drop_table('customercreditentry')
    op.drop_index(op.f('ix_customer_telegram_user_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_business_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_branch_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_balance'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###

