"""add_rbac_branch_invite_models

Revision ID: 1991694fbf44
Revises: cac65bee126c
Create Date: 2025-11-29 05:27:58.489473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1991694fbf44'
down_revision: Union[str, None] = 'cac65bee126c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_business_id'), 'branch', ['business_id'], unique=False)
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_business_id'), 'invite', ['business_id'], unique=False)
    op.create_index(op.f('ix_invite_code'), 'invite', ['code'], unique=True)
    op.add_column('activity_log', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('activity_log', sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('activity_log', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_activity_log_user_id'), 'activity_log', ['user_id'], unique=False)
    op.create_foreign_key(None, 'activity_log', 'user', ['user_id'], ['id'])
    op.add_column('business', sa.Column('allow_staff_stock_adjustments', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('business', sa.Column('show_sensitive_data', sa.Boolean(), nullable=True, server_default='true'))
    op.add_column('business', sa.Column('invoice_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE business SET allow_staff_stock_adjustments = false WHERE allow_staff_stock_adjustments IS NULL")
    op.execute("UPDATE business SET show_sensitive_data = true WHERE show_sensitive_data IS NULL")
    op.alter_column('business', 'allow_staff_stock_adjustments', existing_type=sa.Boolean(), nullable=False, server_default=None)
    op.alter_column('business', 'show_sensitive_data', existing_type=sa.Boolean(), nullable=False, server_default=None)
    op.add_column('inventorymovement', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inventorymovement_branch_id'), 'inventorymovement', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'inventorymovement', 'branch', ['branch_id'], ['id'])
    op.add_column('invoice', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invoice_branch_id'), 'invoice', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'invoice', 'branch', ['branch_id'], ['id'])
    op.add_column('product', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_branch_id'), 'product', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'product', 'branch', ['branch_id'], ['id'])
    op.add_column('purchase', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('purchase', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_branch_id'), 'purchase', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'purchase', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'purchase', 'branch', ['branch_id'], ['id'])
    op.add_column('user', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default='staff'))
    op.execute("UPDATE \"user\" SET role = 'owner' WHERE role IS NULL")
    op.alter_column('user', 'role', existing_type=sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=None)
    op.add_column('user', sa.Column('business_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('pin_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_branch_id'), 'user', ['branch_id'], unique=False)
    op.create_index(op.f('ix_user_business_id'), 'user', ['business_id'], unique=False)
    op.create_foreign_key(None, 'user', 'branch', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'user', 'business', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_business_id'), table_name='user')
    op.drop_index(op.f('ix_user_branch_id'), table_name='user')
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'pin_hash')
    op.drop_column('user', 'branch_id')
    op.drop_column('user', 'business_id')
    op.drop_column('user', 'role')
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_branch_id'), table_name='purchase')
    op.drop_column('purchase', 'created_by')
    op.drop_column('purchase', 'branch_id')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_index(op.f('ix_product_branch_id'), table_name='product')
    op.drop_column('product', 'branch_id')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_branch_id'), table_name='invoice')
    op.drop_column('invoice', 'branch_id')
    op.drop_constraint(None, 'inventorymovement', type_='foreignkey')
    op.drop_index(op.f('ix_inventorymovement_branch_id'), table_name='inventorymovement')
    op.drop_column('inventorymovement', 'branch_id')
    op.drop_column('business', 'invoice_template')
    op.drop_column('business', 'show_sensitive_data')
    op.drop_column('business', 'allow_staff_stock_adjustments')
    op.drop_constraint(None, 'activity_log', type_='foreignkey')
    op.drop_index(op.f('ix_activity_log_user_id'), table_name='activity_log')
    op.drop_column('activity_log', 'entity_id')
    op.drop_column('activity_log', 'entity_type')
    op.drop_column('activity_log', 'user_id')
    op.drop_index(op.f('ix_invite_code'), table_name='invite')
    op.drop_index(op.f('ix_invite_business_id'), table_name='invite')
    op.drop_table('invite')
    op.drop_index(op.f('ix_branch_business_id'), table_name='branch')
    op.drop_table('branch')
    # ### end Alembic commands ###

