"""add_subscription_fields_to_user

Revision ID: 25530abc9af9
Revises: 74751a145873
Create Date: 2025-11-28 11:42:24.160751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '25530abc9af9'
down_revision: Union[str, None] = '74751a145873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value first
    op.add_column('user', sa.Column('subscription_status', sa.String(), nullable=False, server_default='free'))
    op.add_column('user', sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
    # Remove server default after adding column
    op.alter_column('user', 'subscription_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscription_expires_at')
    op.drop_column('user', 'subscription_status')
    # ### end Alembic commands ###

