"""add_subscription_models

Revision ID: 525721140fe0
Revises: 1991694fbf44
Create Date: 2025-11-29 09:22:36.741799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '525721140fe0'
down_revision: Union[str, None] = '1991694fbf44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptionplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=False),
    sa.Column('price_yearly', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_products', sa.Integer(), nullable=True),
    sa.Column('max_invoices', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_branches', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptionplan_code'), 'subscriptionplan', ['code'], unique=True)
    op.create_table('usersubscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('payment_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('billing_cycle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersubscription_plan_code'), 'usersubscription', ['plan_code'], unique=False)
    op.create_index(op.f('ix_usersubscription_user_id'), 'usersubscription', ['user_id'], unique=False)
    op.create_table('paymenttransaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['usersubscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymenttransaction_transaction_reference'), 'paymenttransaction', ['transaction_reference'], unique=True)
    op.create_index(op.f('ix_paymenttransaction_user_id'), 'paymenttransaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paymenttransaction_user_id'), table_name='paymenttransaction')
    op.drop_index(op.f('ix_paymenttransaction_transaction_reference'), table_name='paymenttransaction')
    op.drop_table('paymenttransaction')
    op.drop_index(op.f('ix_usersubscription_user_id'), table_name='usersubscription')
    op.drop_index(op.f('ix_usersubscription_plan_code'), table_name='usersubscription')
    op.drop_table('usersubscription')
    op.drop_index(op.f('ix_subscriptionplan_code'), table_name='subscriptionplan')
    op.drop_table('subscriptionplan')
    # ### end Alembic commands ###

