"""add_admin_sync_models

Revision ID: 929009d00a10
Revises: 0a8c28a95feb
Create Date: 2025-11-30 11:37:47.067293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '929009d00a10'
down_revision: Union[str, None] = '0a8c28a95feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businessmetricsdaily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('total_sales', sa.Float(), nullable=False),
    sa.Column('total_invoices', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('total_expenses', sa.Float(), nullable=False),
    sa.Column('expense_count', sa.Integer(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('customers_count', sa.Integer(), nullable=False),
    sa.Column('new_customers', sa.Integer(), nullable=False),
    sa.Column('credit_sales', sa.Float(), nullable=False),
    sa.Column('stock_value', sa.Float(), nullable=False),
    sa.Column('stock_movements', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'branch_id', 'metric_date', name='uq_business_metrics')
    )
    op.create_index(op.f('ix_businessmetricsdaily_branch_id'), 'businessmetricsdaily', ['branch_id'], unique=False)
    op.create_index(op.f('ix_businessmetricsdaily_business_id'), 'businessmetricsdaily', ['business_id'], unique=False)
    op.create_index(op.f('ix_businessmetricsdaily_metric_date'), 'businessmetricsdaily', ['metric_date'], unique=False)
    op.create_table('systemhealth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('component', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemhealth_metric_name'), 'systemhealth', ['metric_name'], unique=False)
    op.create_index(op.f('ix_systemhealth_timestamp'), 'systemhealth', ['timestamp'], unique=False)
    op.create_table('adminlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('after_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adminlog_action'), 'adminlog', ['action'], unique=False)
    op.create_index(op.f('ix_adminlog_admin_id'), 'adminlog', ['admin_id'], unique=False)
    op.create_index(op.f('ix_adminlog_created_at'), 'adminlog', ['created_at'], unique=False)
    op.create_table('syncerror',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_msg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('sync_action_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncerror_business_id'), 'syncerror', ['business_id'], unique=False)
    op.create_index(op.f('ix_syncerror_created_at'), 'syncerror', ['created_at'], unique=False)
    op.create_index(op.f('ix_syncerror_error_type'), 'syncerror', ['error_type'], unique=False)
    op.create_index(op.f('ix_syncerror_resolved'), 'syncerror', ['resolved'], unique=False)
    op.create_table('syncevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncevent_branch_id'), 'syncevent', ['branch_id'], unique=False)
    op.create_index(op.f('ix_syncevent_business_id'), 'syncevent', ['business_id'], unique=False)
    op.create_index(op.f('ix_syncevent_created_at'), 'syncevent', ['created_at'], unique=False)
    op.create_index(op.f('ix_syncevent_event_type'), 'syncevent', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syncevent_event_type'), table_name='syncevent')
    op.drop_index(op.f('ix_syncevent_created_at'), table_name='syncevent')
    op.drop_index(op.f('ix_syncevent_business_id'), table_name='syncevent')
    op.drop_index(op.f('ix_syncevent_branch_id'), table_name='syncevent')
    op.drop_table('syncevent')
    op.drop_index(op.f('ix_syncerror_resolved'), table_name='syncerror')
    op.drop_index(op.f('ix_syncerror_error_type'), table_name='syncerror')
    op.drop_index(op.f('ix_syncerror_created_at'), table_name='syncerror')
    op.drop_index(op.f('ix_syncerror_business_id'), table_name='syncerror')
    op.drop_table('syncerror')
    op.drop_index(op.f('ix_adminlog_created_at'), table_name='adminlog')
    op.drop_index(op.f('ix_adminlog_admin_id'), table_name='adminlog')
    op.drop_index(op.f('ix_adminlog_action'), table_name='adminlog')
    op.drop_table('adminlog')
    op.drop_index(op.f('ix_systemhealth_timestamp'), table_name='systemhealth')
    op.drop_index(op.f('ix_systemhealth_metric_name'), table_name='systemhealth')
    op.drop_table('systemhealth')
    op.drop_index(op.f('ix_businessmetricsdaily_metric_date'), table_name='businessmetricsdaily')
    op.drop_index(op.f('ix_businessmetricsdaily_business_id'), table_name='businessmetricsdaily')
    op.drop_index(op.f('ix_businessmetricsdaily_branch_id'), table_name='businessmetricsdaily')
    op.drop_table('businessmetricsdaily')
    # ### end Alembic commands ###

