"""add_stock_take_models

Revision ID: a1e89fa56d58
Revises: a216d9033325
Create Date: 2025-11-29 10:59:02.971981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1e89fa56d58'
down_revision: Union[str, None] = 'a216d9033325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocktakesession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_items_counted', sa.Integer(), nullable=False),
    sa.Column('total_differences', sa.Integer(), nullable=False),
    sa.Column('total_loss_value', sa.Float(), nullable=False),
    sa.Column('total_gain_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocktakesession_business_id'), 'stocktakesession', ['business_id'], unique=False)
    op.create_index(op.f('ix_stocktakesession_user_id'), 'stocktakesession', ['user_id'], unique=False)
    op.create_table('stockadjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('previous_qty', sa.Integer(), nullable=False),
    sa.Column('new_qty', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('adjustment_value', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('adjusted_by', sa.Integer(), nullable=False),
    sa.Column('adjusted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adjusted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['stocktakesession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stockadjustment_business_id'), 'stockadjustment', ['business_id'], unique=False)
    op.create_index(op.f('ix_stockadjustment_product_id'), 'stockadjustment', ['product_id'], unique=False)
    op.create_table('stocktakeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected_qty', sa.Integer(), nullable=False),
    sa.Column('counted_qty', sa.Integer(), nullable=True),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('difference_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('difference_value', sa.Float(), nullable=False),
    sa.Column('counted_at', sa.DateTime(), nullable=True),
    sa.Column('counted_by', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['counted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['stocktakesession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocktakeline_product_id'), 'stocktakeline', ['product_id'], unique=False)
    op.create_index(op.f('ix_stocktakeline_session_id'), 'stocktakeline', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocktakeline_session_id'), table_name='stocktakeline')
    op.drop_index(op.f('ix_stocktakeline_product_id'), table_name='stocktakeline')
    op.drop_table('stocktakeline')
    op.drop_index(op.f('ix_stockadjustment_product_id'), table_name='stockadjustment')
    op.drop_index(op.f('ix_stockadjustment_business_id'), table_name='stockadjustment')
    op.drop_table('stockadjustment')
    op.drop_index(op.f('ix_stocktakesession_user_id'), table_name='stocktakesession')
    op.drop_index(op.f('ix_stocktakesession_business_id'), table_name='stocktakesession')
    op.drop_table('stocktakesession')
    # ### end Alembic commands ###

