"""add_supplier_and_purchase_tables

Revision ID: d7b117bf5ea8
Revises: 001
Create Date: 2025-11-27 07:07:22.647227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b117bf5ea8'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_business_id'), 'supplier', ['business_id'], unique=False)
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_business_id'), 'purchase', ['business_id'], unique=False)
    op.create_index(op.f('ix_purchase_purchase_number'), 'purchase', ['purchase_number'], unique=True)
    op.create_index(op.f('ix_purchase_supplier_id'), 'purchase', ['supplier_id'], unique=False)
    op.create_table('purchaseitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('invoice_invoice_number_key', 'invoice', type_='unique')
    op.create_index(op.f('ix_invoice_invoice_number'), 'invoice', ['invoice_number'], unique=True)
    op.drop_constraint('invoiceitem_invoice_id_fkey', 'invoiceitem', type_='foreignkey')
    op.create_foreign_key(None, 'invoiceitem', 'invoice', ['invoice_id'], ['id'])
    op.alter_column('legacy_stock_item', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint('user_telegram_id_key', 'user', type_='unique')
    op.drop_index('ix_user_telegram_id', table_name='user')
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.create_index('ix_user_telegram_id', 'user', ['telegram_id'], unique=False)
    op.create_unique_constraint('user_telegram_id_key', 'user', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('legacy_stock_item', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'invoiceitem', type_='foreignkey')
    op.create_foreign_key('invoiceitem_invoice_id_fkey', 'invoiceitem', 'invoice', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_invoice_invoice_number'), table_name='invoice')
    op.create_unique_constraint('invoice_invoice_number_key', 'invoice', ['invoice_number'], postgresql_nulls_not_distinct=False)
    op.drop_table('purchaseitem')
    op.drop_index(op.f('ix_purchase_supplier_id'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_purchase_number'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_business_id'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_supplier_business_id'), table_name='supplier')
    op.drop_table('supplier')
    # ### end Alembic commands ###

