"""add_product_fields_barcode_reorder_supplier

Revision ID: dbc4fe5d5065
Revises: 25530abc9af9
Create Date: 2025-11-28 12:30:45.658080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dbc4fe5d5065'
down_revision: Union[str, None] = '25530abc9af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoiceauditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoiceauditlog_invoice_id'), 'invoiceauditlog', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoiceauditlog_timestamp'), 'invoiceauditlog', ['timestamp'], unique=False)
    op.add_column('invoice', sa.Column('discount', sa.Float(), nullable=False, server_default='0'))
    op.add_column('invoice', sa.Column('template', sa.String(), nullable=False, server_default="'simple'"))
    op.add_column('invoice', sa.Column('payment_mode', sa.String(), nullable=False, server_default="'cash'"))
    # Remove server defaults after adding
    op.alter_column('invoice', 'discount', server_default=None)
    op.alter_column('invoice', 'template', server_default=None)
    op.alter_column('invoice', 'payment_mode', server_default=None)
    op.add_column('invoice', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('invoice', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoice', 'user', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'invoice', 'user', ['created_by'], ['id'])
    op.add_column('product', sa.Column('barcode', sa.String(), nullable=True))
    op.add_column('product', sa.Column('reorder_quantity', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_barcode'), 'product', ['barcode'], unique=False)
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=False)
    op.create_foreign_key(None, 'product', 'supplier', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_index(op.f('ix_product_barcode'), table_name='product')
    op.drop_column('product', 'supplier_id')
    op.drop_column('product', 'reorder_quantity')
    op.drop_column('product', 'barcode')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_column('invoice', 'updated_by')
    op.drop_column('invoice', 'created_by')
    op.drop_column('invoice', 'template')
    op.drop_column('invoice', 'discount')
    op.drop_index(op.f('ix_invoiceauditlog_timestamp'), table_name='invoiceauditlog')
    op.drop_index(op.f('ix_invoiceauditlog_invoice_id'), table_name='invoiceauditlog')
    op.drop_table('invoiceauditlog')
    # ### end Alembic commands ###

